upstream tomcat {
  server <<tomcat_server>>:8080 weight=100 max_fails=5 fail_timeout=5;
}

server {
  server_name     <<server_name>>
  root /www/data;

  location /app {
    return 302 /app/;
  }
  location /app/ {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header Origin $host;
        proxy_set_header Host $host;
        proxy_pass http://tomcat/lazerwiki/;
        add_header Access-Control-Allow-Headers *;

        proxy_cookie_path ~^/(.*) /;
  }
  location /_media/ {
	client_max_body_size 0;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header Origin $host;
        proxy_set_header Host $host;
        proxy_pass http://tomcat/lazerwiki/_media/;
        add_header Access-Control-Allow-Headers *;

        proxy_cookie_path ~^/(.*) /;
  }
  
  location /_resources/ {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header Origin $host;
        proxy_set_header Host $host;
        proxy_pass http://tomcat/lazerwiki/_resources/;
        add_header Access-Control-Allow-Headers *;

        proxy_cookie_path ~^/(.*) /;
  }
  
  
  location = / {
        add_header Pragma "no-cache";
        add_header Cache-Control "no-store,no-cache,must-revalidate";
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header Origin $host;
        proxy_pass http://tomcat/lazerwiki-ui/;
  }
  
  location = /meta.json {
        add_header Pragma "no-cache";
        add_header Cache-Control "no-store,no-cache,must-revalidate";
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header Origin $host;
        proxy_pass http://tomcat/lazerwiki-ui/meta.json;
  }
  
  location = /sitemap.xml {
        add_header Pragma "no-cache";
        add_header Cache-Control "no-store,no-cache,must-revalidate";
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header Origin $host;
        proxy_set_header Host $host;
        proxy_pass http://tomcat/lazerwiki/sitemap.xml;
  }
  
  location  / {
        rewrite /page/(.*) /lazerwiki-ui/  break;   	
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header Origin $host;
        proxy_pass http://tomcat/lazerwiki-ui/;
  }


    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate <<ssl-cert-loc>>/fullchain.pem; # managed by Certbot
    ssl_certificate_key <<ssl-cert-loc>>/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot







}

server {
        return 301 https://$host$request_uri;


  server_name     <<server_name>>
  
    listen 80;
    listen          [::]:80;
    return 404; # managed by Certbot


}
